<a href="https://colab.research.google.com/github/Psyche-1/goit-ds-hw/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'2.0.2'

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
v_1 = np.array([1,2,3,4,5,6,7,8,9,10])
v_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [4]:
m_1 = np.zeros((3,3))
m_1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [7]:
a_1 = np.random.randint(1, 11, (5, 5))
a_1

array([[ 6,  7,  5,  8,  1],
       [ 8,  5,  4,  5,  8],
       [ 6,  5, 10,  9,  9],
       [ 1,  1,  5,  1,  5],
       [ 2,  6,  1,  5, 10]])

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [11]:
a_2 = np.random.random(size=(4, 4))
a_2

array([[0.44242308, 0.90076967, 0.94646644, 0.39812635],
       [0.34543638, 0.22430381, 0.2647004 , 0.3908789 ],
       [0.56218131, 0.84971994, 0.63342041, 0.21464004],
       [0.81765643, 0.98190068, 0.15310526, 0.86335174]])

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [23]:
a_3 = np.random.randint(1, 11, 5)
print(a_3)
a_4 = np.random.randint(1, 11, 5)
print(a_4)
print('додавання', a_3 + a_4)
print('віднімання', a_3 - a_4)
print('віднімання', a_4 - a_3)
print('множення', a_3 * a_4)

[6 1 4 7 5]
[ 7  1  7 10  8]
додавання [13  2 11 17 13]
віднімання [-1  0 -3 -3 -3]
віднімання [1 0 3 3 3]
множення [42  1 28 70 40]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [24]:
v_2 = np.random.randint(1, 11, 7)
print(v_2)
v_3 = np.random.randint(1, 11, 7)
print(v_3)
print(np.dot(v_2, v_3))

[3 3 8 7 8 1 6]
[9 6 2 8 1 4 8]
177


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [34]:
m_2 = np.random.randint(1, 11, (2, 2))
print(m_2)
m_3 = np.random.randint(1, 11, (2,3))
print(m_3)
print(np.dot(m_2, m_3))
# print(np.dot(m_3, m_2)) неможливо

[[4 7]
 [2 4]]
[[5 4 3]
 [4 4 6]]
[[48 44 54]
 [26 24 30]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [36]:
m_4 = np.random.randint(1, 11, (3, 3))
m_4.T

array([[ 8,  4,  4],
       [ 3, 10,  6],
       [ 3,  5,  3]])

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [37]:
m_5 = np.random.random(size=(4, 4))
m_5.T

array([[0.29074996, 0.35148395, 0.13883431, 0.72605148],
       [0.02411706, 0.64799232, 0.7143561 , 0.04489119],
       [0.05288106, 0.31782452, 0.43079421, 0.97130522],
       [0.59063206, 0.50046314, 0.95449493, 0.61488759]])

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [40]:
m_6 = np.random.randint(1, 11, (3, 4))
v_4 = np.random.randint(1, 11, 4)
np.dot(m_6, v_4)

[[36  6 40 45]
 [90 12 90  5]
 [63 18 50 45]]


array([127, 197, 176])

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [41]:
m_7 = np.random.random(size=(2, 3))
v_4 = np.random.random(size=(3))
np.dot(m_7, v_4)

array([0.41170471, 0.08510385])

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [42]:
m_8 = np.random.randint(1, 11, (2, 2))
m_9 = np.random.randint(1, 11, (2, 2))
m_8 * m_9

array([[20, 50],
       [80, 18]])

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [43]:
m_10 = np.random.randint(1, 11, (2, 2))
m_11 = np.random.randint(1, 11, (2, 2))
np.dot(m_10, m_11)

array([[142, 138],
       [ 24,  25]])

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [44]:
m_12 = np.random.randint(1, 101, (5, 5))
np.sum(m_12)

np.int64(1354)

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [45]:
m_13 = np.random.randint(1, 11, (4, 4))
m_14 = np.random.randint(1, 11, (4, 4))
m_13 - m_14

array([[-2,  5,  8, -2],
       [ 0,  4,  2, -5],
       [ 1, -7, -4, -2],
       [ 0,  4,  0, -2]])

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [60]:
m_15 = np.random.random(size=(3, 3))
print(m_15)
np.sum(m_15, axis=1).reshape(-1, 1)

[[0.69342882 0.70926414 0.95055792]
 [0.37511212 0.68618414 0.86677942]
 [0.1585227  0.16544942 0.60216307]]


array([[2.35325088],
       [1.92807568],
       [0.92613519]])

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [61]:
m_16 = np.random.randint(1, 11, (3, 4))
m_17 = np.pow(m_16, 2)
m_17

array([[ 49,  81,  81,   1],
       [ 36,   1,  25,  81],
       [ 36,   9, 100,  64]])

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [70]:
v_5 = np.random.randint(1, 51, 4)
np.sqrt(v_5)

array([5.74456265, 6.70820393, 5.        , 4.47213595])

# Завдання 2

1. Замініть усі непарні числа в arr на -1 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

2. Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками

In [75]:
arr_2 = np.array([1,2,3,4,5,6])
arr_2.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

3. Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально

In [76]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

4. Створіть наступний шаблон без жорсткого кодування(Hard coding) . Використовуйте лише функції Numpy і наведений нижче масив введення Input:a = np.array([1,2,3])

Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [78]:
a = np.array([1,2,3])
repeated = np.repeat(a, 3)
tiled = np.tile(a, 3)
output = np.concatenate((repeated, tiled))
output

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

5. Отримайте спільні елементи між a і b

a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

In [79]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

6. Отримайте позиції перших 5 максимальних значень у заданому масиві a

np.random.seed(100) a = np.random.uniform(1,50, 20)

In [87]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
np.argsort(a)[-5:][::-1]

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]


array([15, 10,  3,  7, 18])

7. Вилучіть усі значення NaN із одновимірного масиву

а=np.array([1,2,3,np.nan,5,6,7,np.nan])

In [95]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
result = a[~np.isnan(a)]
result

array([1., 2., 3., 5., 6., 7.])

8. Обчисліть евклідову відстань між двома масивами a і b.

a = np.array([1,2,3,4,5]) b = np.array([4,5,6,7,8])

In [96]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
np.linalg.norm(a - b)

np.float64(6.708203932499369)

9. Знайдіть індекс 5-го повторення числа 1 у масиві x

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [100]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
np.where(x == 1)[0][4]

np.int64(8)

10. Знайдіть повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначте їх як True. Перше повторення має бути False.

Input np.random.seed(100) a = np.random.randint(0, 5, 10)

[0 0 3 0 2 4 2 2 2 2] #Output [False True False True False False True True True True]

In [103]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
mask = np.full(a.shape, False)
_, first_indices = np.unique(a, return_index=True)
mask[np.isin(np.arange(a.size), first_indices, invert=True)] = True
mask

array([False,  True, False,  True, False, False,  True,  True,  True,
        True])